nodeLinker: node-modules

enableGlobalCache: false

compressionLevel: mixed

enableTelemetry: false

# 网络配置
httpTimeout: 60000
networkTimeout: 60000

# 安装配置
preferInteractive: false

# CI 环境配置 - 允许在 CI 中更新 lockfile
enableImmutableInstalls: false
